name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Bing bong'
        required: false
        default: 'Bing'
        type: choice
        options:
          - Bing
          - Bong
          - Ding
  push:
    branches: [master]
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: compile
        run: |
          npm i --include=dev
          cd foodle
          npm run build
      - name: Commit to the repo
        run: |
          git config --global user.name "Jason | Build updater"
          git config --global user.email "JasonCameron.all@gmail.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update build files' || echo
          git push
      
