name: UpdateSitemap


on:
  page_build:
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
            drop-html-extension: true
            base-url-path: https://nasoj.me

      - name: commit files
        run: |
          git config --global user.name "Jason | Sitemap updater"
          git config --global user.email "thebosssg19@gmail.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update gallary file' || echo
          git push
      

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master


      - name: notify google/bing that there is a new sitemap
        env:
          CUSTOM_URL: "${{ secrets.SITEMAP_URL }}" # set custom URL if you use it
          SITEMAP_FILE: "sitemap.xml"
        run: |
          if [ -z "${CUSTOM_URL}" ]; then
            if [ -s "CNAME" ]; then
              MAP_URL="$(cat CNAME)"
            else
              MAP_URL="$(echo ${{ github.repository }} | sed -e "s/^.*${{ github.github.repository_owner }}\///")"
            fi
              MAP_URL="https://${MAP_URL}/${SITEMAP_FILE}"
          else
            MAP_URL="${CUSTOM_URL}"
          fi
          
          curl -v "https://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "https://www.bing.com/ping?sitemap=${MAP_URL}" &> /dev/null  &
          wait
          printf "\n\nDone\n"
          
